#platform :ios, '13.0'
use_frameworks!

target 'NovastoneCodeTest' do  
  pod 'IGListKit', '~> 4.0.0'
  pod 'Alamofire', '~> 5.2'
end

target 'NovastoneCodeTestTests' do
  pod 'Nimble', '~> 8.1.1'
end